### PR TITLE
2 best gamemodes

### PR DESCRIPTION
**Pull request by Effectism**
I won't make PRs to the wrong repo a third time I swear

### CODE REVIEW

**Comment by MCterra10** [comment]
Will test review, testmerge and eventually fullmerge when I have time

**Comment by MCterra10** [comment]
Branch will get testmerged today

**Comment by MCterra10** [comment]
rerunning test. something went wrong when this attempted to build

**Comment by MCterra10** [comment]
@Effectism please resolve the bugs in this code

**Comment by MCterra10** [comment]
lmao floydmats. fucking over coders since their inception

**Comment by Effectism** [comment]
conversion machine broke

**Comment by MCterra10** [comment]
Travis failed, but it might be unrelated

**Pull request merged**
