### PR TITLE
Plaque butchery attempt 3

### PR DESCRIPTION
**Pull request by Effectism**
## About The Pull Request

Custom plaques, this time they're a map modification instead of an icon replacement. This may be better or worse.

### CODE REVIEW

**Comment by MCterra10** [comment]
You'll need to use the map merger to properly update the map and avoid conflicts. Please use https://tgstation13.org/wiki/Map_Merger and push the changes to this branch

**Comment by MCterra10** [comment]
I'm confused, there is no change to the map file now

**Comment by MCterra10** [comment]
looking much better, I'll compile locally and test

**Comment by Effectism** [comment]
Reverted the map file before re-doing the changes with map merger.

**Comment by MCterra10** [comment]
two things:
please make sure you use consistent line endings in all text files (code or otherwise). The files you edited used LF so you'll need to make sure that's what you used. Also, please make sure each text file has one newline on the end

**Comment by Effectism** [comment]
checks finally passed, impressive

**Comment by MCterra10** [comment]
good to go!

**Pull request merged**
